import axios from "axios";

const BASE_URL = "https://dev-34194375.okta.com";
const CLIENT_API_KEY = process.env.REACT_APP_CLIENT_API_KEY;

const apiService = axios.create({
  baseURL: BASE_URL,
  headers: {
    "x-api-key": CLIENT_API_KEY,
    "Content-Type": "application/json",
  },
});

export const authenticateUser = (idToken: string) => {
  return apiService.post("/api/v1/authenticate", { id_token: idToken });
};

export const setPin = (idToken: string, token: string, reloginPin: string) => {
  return apiService.post("/api/v1/set_pin", {
    id_token: idToken,
    token: token,
    relogin_pin: reloginPin,
    purpose: "set_pin",
  });
};

export const createWallet = (authToken: string) => {
  return apiService.post(
    "/api/v1/wallet",
    {},
    {
      headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
    }
  );
};

export const refreshToken = (
  authToken: string,
  refreshToken: string,
  deviceToken: string
) => {
  return apiService.post(
    "/api/v1/refresh_token",
    {},
    {
      headers: {
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4`,
        "x-refresh-authorization": `Bearer ${refreshToken}`,
        "x-device-token": deviceToken,
      },
    }
  );
};

export const logoutUser = (authToken: string) => {
  return apiService.post(
    "/api/v1/logout",
    {},
    {
      headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
    }
  );
};

export const getUserDetails = (authToken: string) => {
  return apiService.get("/api/v1/user_from_token", {
    headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
  });
};

export const getWallets = (authToken: string) => {
  return apiService.get("/api/v1/wallet", {
    headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
  });
};

export const getSupportedNetworks = (authToken: string) => {
  return apiService.get("/api/v1/supported/networks", {
    headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
  });
};

export const getSupportedTokens = (authToken: string, page = 1, size = 10) => {
  return apiService.get(`/api/v1/supported/tokens?page=${page}&size=${size}`, {
    headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
  });
};

export const getUserPortfolio = (authToken: string) => {
  return apiService.get("/api/v1/portfolio", {
    headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
  });
};

export const getUserPortfolioActivity = (
  authToken: string,
  limit = 10,
  offset = 0
) => {
  return apiService.get(
    `/api/v1/portfolio/activity?limit=${limit}&offset=${offset}`,
    {
      headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
    }
  );
};

// TODO
export const transferTokens = (authToken: string, data: any) => {
  return apiService.post("/api/v1/transfers/tokens/execute", data, {
    headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
  });
};

export const getOrdersHistory = (
  authToken: string,
  offset = 0,
  limit = 10,
  orderId?: string,
  orderState?: string
) => {
  let url = `/api/v1/orders?offset=${offset}&limit=${limit}`;
  if (orderId) url += `&order_id=${orderId}`;
  if (orderState) url += `&order_state=${orderState}`;

  return apiService.get(url, {
    headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
  });
};

export const executeRawTransaction = (authToken: string, data: any) => {
  return apiService.post("/api/v1/rawtransaction/execute", data, {
    headers: { Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2luZGN4X2lkIjoiNmY3OWU4NjktMTBjYS00OTFhLWJkYzUtZTlhNGRiNjIwMDk1IiwidXNlcl9pZCI6IjZmNzllODY5LTEwY2EtNDkxYS1iZGM1LWU5YTRkYjYyMDA5NSIsInNoYXJlZF9pZCI6bnVsbCwiZGN4X2NyZWF0ZWRfYXQiOm51bGwsInBvcnRmb2xpb0ZhY3RvciI6IjEiLCJhY2NUeXBlIjoid2ViMyIsImFjY291bnRfb3duZXJfaWQiOiJjNTcwMzA0Yi1hOTkwLTVkMGMtYTViZi1hYTI5ODk0ZjQ4MTciLCJzZXNzaW9uSWQiOiI2ZTU5OGEyMC1iZWJjLTRkZGUtYTFkYy1jNmU2NGM0ODNmOTMiLCJ1c2VyX2xvZ2luX3ZlbmRvcl9pZCI6ImY1OGEzOWU2LTlhNTctNGQ0Ny05ZmI5LWJkOWIzZjZhYzZhNiIsInMiOiJ3ZWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJzaXAiOiIxNTIuNTguMjMwLjYwIiwic2NpdHkiOiJCZW5nYWx1cnUiLCJzY291bnRyeSI6IklOIiwic3JlZ2lvbiI6IktBIiwibG9naW5fbWVkaXVtIjoiR19BVVRIIiwiaWF0IjoxNzMzNTk4MjQwLCJleHAiOjE3MzQ0NjIyNDB9.YQ6Vgv0MZ33T_rY0_wj-tQSQTFam-zZnBbui3HuVmb4` },
  });
};
